[tool.pylint]
extension-pkg-allow-list = ["cv2", "numpy"]
ignore = ["__pycache__"]

[tool.pylint.messages_control]
disable = [
  "invalid-name",                 # e.g. x, y, t, K common in CV/math
  "missing-module-docstring",
  "missing-function-docstring",
  "missing-class-docstring",
  "no-member",
  "unpacking-non-sequence",
  "multiple-statements",
  "redefined-outer-name",
  "broad-exception-caught",
  "unused-import",
  "import-outside-toplevel",     # (optional) disable globally
  "multiple-imports"             # Allow grouped imports when logical
]

[tool.pylint.typecheck]
generated-members = [
  "cv2.*",
  "cv2.aruco.*"
]

[tool.pylint.format]
max-line-length = 250
