[tool.pylint]
# allow compiled/extension packages
extension-pkg-allow-list = ["cv2", "numpy", "dateutil"]
ignore = ["__pycache__"]

[tool.pylint.messages_control]
disable = [
  "invalid-name",
  "missing-module-docstring",
  "missing-function-docstring",
  "missing-class-docstring",
  "no-member",
  "unpacking-non-sequence",
  "multiple-statements",
  "redefined-outer-name",
  "broad-exception-caught",
  "unused-import",            # <– keep this
  "import-outside-toplevel",
  "multiple-imports"
]

[tool.pylint.typecheck]
generated-members = [
  "cv2.*",
  "cv2.aruco.*"
]

[tool.pylint.format]
max-line-length = 250

[tool.pyright]            # <— new section
reportMissingModuleSource = false
venvPath = "."
venv = ".venv"
pythonVersion = "3.10"
