"""Constants used throughout the application."""

# Time constants
DAYS_PER_MONTH = 30
DAYS_PER_YEAR = 365
MONTHS_PER_YEAR = 12

# Default time periods
DEFAULT_ABSTRACT_ADVANCE_DAYS = 30
DEFAULT_LOOKAHEAD_DAYS = 30
DEFAULT_POSTER_DURATION_DAYS = 30
DEFAULT_CONFERENCE_RESPONSE_DAYS = 90
DEFAULT_PLOT_EXTENSION_DAYS = 90

# Configurable defaults (from config files)
DEFAULT_MIN_ABSTRACT_LEAD_TIME_DAYS = 30
DEFAULT_MIN_PAPER_LEAD_TIME_DAYS = 60
DEFAULT_MAX_CONCURRENT_SUBMISSIONS = 2
DEFAULT_PAPER_LEAD_TIME_MONTHS = 3

# Priority weights (from config files)
DEFAULT_ENGINEERING_PAPER_WEIGHT = 2.0
DEFAULT_MEDICAL_PAPER_WEIGHT = 1.0
DEFAULT_MOD_WEIGHT = 1.5
DEFAULT_ABSTRACT_WEIGHT = 0.5

# Penalty costs (from config files)
DEFAULT_MOD_PENALTY_PER_DAY = 1000.0
DEFAULT_PAPER_PENALTY_PER_DAY = 500.0

# Scoring constants
MAX_SCORE = 100.0
MIN_SCORE = 0.0
PERCENTAGE_MULTIPLIER = 100.0

# Penalty constants (from penalty.py)
DEFAULT_PENALTY_PER_DAY = 100.0
SPECIAL_J19_J20_PENALTY = 3000.0
SPECIAL_J19_J20_YEAR_PENALTY = 10000.0
MISSED_ABSTRACT_PENALTY = 3000.0
TECHNICAL_AUDIENCE_LOSS_PENALTY = 3000.0
AUDIENCE_MISMATCH_PENALTY = 1500.0

# Efficiency constants (from efficiency.py)
OPTIMAL_UTILIZATION_RATE = 0.8  # 80%
UTILIZATION_DEVIATION_PENALTY = 100.0
TIMELINE_EFFICIENCY_SHORT_PENALTY = 0.5
TIMELINE_EFFICIENCY_LONG_PENALTY = 0.8
IDEAL_DAYS_PER_SUBMISSION = 30

# Quality constants (from quality.py)
ROBUSTNESS_SCALE_FACTOR = 10.0
BALANCE_VARIANCE_FACTOR = 10.0
SINGLE_SUBMISSION_ROBUSTNESS = 100.0
SINGLE_SUBMISSION_BALANCE = 100.0

# Validation constants (from constraints.py)
PERFECT_COMPLIANCE_RATE = 100.0
ZERO_COMPLIANCE_RATE = 0.0

# Display constants (from plots.py, console.py)
MAX_TITLE_LENGTH = 30
DEFAULT_DPI = 300
DEFAULT_PLOT_HEIGHT_PER_ITEM = 30
MIN_PLOT_HEIGHT = 600

# File constants
DEFAULT_JSON_INDENT = 2

# Report constants (from reports.py)
MAX_PENALTY_FACTOR = 0.5
PENALTY_NORMALIZATION_FACTOR = 10000.0

# Scheduler constants (from schedulers)
MAX_BACKTRACK_DAYS = 30
DEFAULT_STOCHASTIC_ITERATIONS = 100
DEFAULT_RANDOM_ITERATIONS = 50

# Date formatting constants (from formatters)
RELATIVE_TIME_THRESHOLD_DAYS = 30
